# Generated by Django 6.1.1 on 2026-09-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nusxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventar_raqami', models.CharField(max_length=30, unique=True)),
                ('holati', models.CharField(choices=[('mavjud', 'Mavjud'), ('berilgan', 'Berilgan'), ('band', 'Band'), ('tamirda', "Ta'mirda"), ('yoqolgan', "Yo'qolgan")], default='mavjud', max_length=30)),
                ('javon', models.CharField(blank=True, max_length=30)),
                ('qabul_sana', models.DateField()),
                ('izoh', models.TextField(blank=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nusxalar', to='kitob.kitob')),
            ],
        ),
    ]
