# Generated by Django 6.1.1 on 2026-09-13 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berilgan_sana', models.DateField(default=datetime.date.today)),
                ('qaytarish_muddati', models.DateField()),
                ('qaytarilgan_sana', models.DateField(blank=True, null=True)),
                ('holati', models.CharField(choices=[('faol', 'Faol'), ('qaytarilgan', 'Qaytarilgan'), ('yoqolgan', "Yo'qolgan")], max_length=20)),
                ('eslatma_yuborilgan', models.BooleanField(default=False)),
            ],
        ),
    ]
