# Generated by Django 6.1.1 on 2026-09-13 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('berish', '0001_initial'),
        ('nusxa', '0001_initial'),
        ('oquvchi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='berish',
            name='bergan_xodim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bergan_berishlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='berish',
            name='nusxa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nusxa.nusxa'),
        ),
        migrations.AddField(
            model_name='berish',
            name='olgan_xodim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='olgan_berishlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='berish',
            name='oquvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oquvchi.oquvchi'),
        ),
    ]
