# Generated by Django 6.1.1 on 2026-09-13 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berish', '0002_initial'),
        ('nusxa', '0001_initial'),
        ('oquvchi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='berish',
            name='holati',
            field=models.CharField(choices=[('faol', 'Faol'), ('qaytarilgan', 'Qaytarilgan'), ('yoqolgan', "Yo'qolgan")], default='faol', max_length=20),
        ),
        migrations.AddIndex(
            model_name='berish',
            index=models.Index(fields=['oquvchi', 'qaytarilgan_sana'], name='berish_oquvchi_qaytarilgan_idx'),
        ),
        migrations.AddIndex(
            model_name='berish',
            index=models.Index(fields=['qaytarish_muddati'], name='berish_muddat_idx'),
        ),
        migrations.AddConstraint(
            model_name='berish',
            constraint=models.UniqueConstraint(condition=models.Q(('qaytarilgan_sana__isnull', True)), fields=('nusxa',), name='bitta_nusxada_bitta_faol_berish'),
        ),
    ]
