# Generated by Django 6.1.1 on 2026-09-13 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=130)),
                ('telefon', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon +998-000-00-00 formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('karta_raqami', models.CharField(max_length=20, unique=True)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('manzil', models.CharField(blank=True, max_length=255)),
                ('royxat_sanasi', models.DateField(auto_now_add=True)),
                ('faol', models.BooleanField(default=True)),
            ],
        ),
    ]
