# Generated by Django 6.1.1 on 2026-09-16 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oquvchi',
            name='telefon',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon +998123456789 formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')]),
        ),
    ]
