# Generated by Django 6.1.1 on 2026-09-24 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0003_drop_orphan_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('fish', models.CharField(max_length=130)),
                ('telefon', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon +998123456789 formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('holati', models.CharField(choices=[('kutmoqda', 'Kutmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('bekor', 'Bekor')], default='kutmoqda', max_length=20)),
                ('ariza_sanasi', models.DateTimeField(auto_now_add=True)),
                ('tasdiqlangan_sana', models.DateTimeField(blank=True, null=True)),
                ('izoh', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-ariza_sanasi'],
            },
        ),
    ]
