# Generated by Django 6.1.1 on 2026-09-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0004_ariza'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='manzil',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ariza',
            name='tugilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
