# Generated by Django 6.1.1 on 2026-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0005_ariza_manzil_ariza_tugilgan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='sinf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='oquvchi',
            name='sinf',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='ariza',
            index=models.Index(fields=['holati', '-ariza_sanasi'], name='ariza_holati_sana_idx'),
        ),
    ]
