# Generated by Django 6.1.1 on 2026-10-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0006_ariza_sinf_oquvchi_sinf_ariza_ariza_holati_sana_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='kasb',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='ariza',
            name='rol',
            field=models.CharField(choices=[('oquvchi', 'Oquvchi'), ('oqituvchi', "O'qituvchi")], default='oquvchi', max_length=20),
        ),
    ]
