# Generated by Django 6.1.1 on 2026-10-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0007_ariza_kasb_ariza_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquvchi',
            name='kasb',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='oquvchi',
            name='rol',
            field=models.CharField(choices=[('oquvchi', 'Oquvchi'), ('oqituvchi', "O'qituvchi")], db_index=True, default='oquvchi', max_length=20),
        ),
    ]
