# Generated by Django 6.1.1 on 2026-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('kutubxonachi', 'Kutubxonachi'), ('administrator', 'Administrator')], default='kutubxonachi', max_length=20),
        ),
    ]
