# Generated by Django 6.1.1 on 2026-09-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('berish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jarima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kechikkan_kunlar', models.PositiveIntegerField()),
                ('kunlik_stavka', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tolandimi', models.BooleanField(default=False)),
                ('tolangan_sana', models.DateTimeField(blank=True, null=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('berish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jarima', to='berish.berish')),
            ],
        ),
    ]
