# Generated by Django 6.1.1 on 2026-09-30 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berish', '0003_alter_berish_holati_and_more'),
        ('jarima', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jarima',
            name='eslatma_yuborilgan_sana',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='jarima',
            index=models.Index(fields=['tolandimi', 'eslatma_yuborilgan_sana'], name='jarima_eslatma_idx'),
        ),
    ]
