"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# apps/ papkasidagi ilovalarni ('user', 'kitob', 'nusxa', ...) to'g'ridan-to'g'ri
# import qilish uchun uni Python qidiruv yo'liga qo'shamiz.
sys.path.insert(0, str(BASE_DIR / "apps"))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-nqg-)@7k5jqqy%16k!4cweb01e7nky$n&^&0b%r%9uektntvv(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

# Production'da (DEBUG=False) ALLOWED_HOSTS bo'sh qolsa Django har bir so'rovga
# "Invalid HTTP_HOST" (400) qaytaradi, shuning uchun uni .env orqali beramiz.
ALLOWED_HOSTS = ["*"] if DEBUG else [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()
]

# HTTPS orqali POST so'rovlarida CSRF tekshiruvi uchun domenni o'zimiz o'zimiz
# tasdiqlaymiz (development'da bu kerak emas).
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'user',
    'rest_framework_simplejwt',
    'nusxa',
    'kitob',
    'berish',
    'navbat',
    'jarima',
    'oquvchi',
    'stats',
    'web',
] 


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'kutubxona'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` yig'gan fayllar shu papkaga tushadi; nginx shu manzildan
# /static/ ni to'g'ridan-to'g'ri beradi (DEBUG=False da Django statik
# fayllarni o'zi bermaydi).
STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'user.User'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Diqqat: Django sozlamasi `MAILERS` emas, `EMAIL_BACKEND` bo'lishi kerak —
# `MAILERS` yozilsa Django standart SMTP backend'ini ishlatadi va
# development'da xatolar chiqadi.

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@kutubxona.local")

# --- Loyiha sozlamalari (spec bo'yicha bitta joyda) ---
MUDDAT_KUN = int(os.environ.get("MUDDAT_KUN", 14))
KUNLIK_JARIMA = int(os.environ.get("KUNLIK_JARIMA", 5000))
LIMIT_KITOB = int(os.environ.get("LIMIT_KITOB", 3))
TAKLIF_SOAT = int(os.environ.get("TAKLIF_SOAT", 24))
# Kitobni qaytarish muddati yaqinlashganda necha kun oldin eslatiladi.
ESLATMA_KUNLAR_OLDIN = int(os.environ.get("ESLATMA_KUNLAR_OLDIN", 2))
# Jarima eslatmasi: task har 3 soatda chaqiriladi, lekin bitta o'quvchiga
# shu soat oralig'idan tez-tez takrorlanib yubormasligi uchun.
JARIMA_ESLATMA_TAKROR_SOAT = int(os.environ.get("JARIMA_ESLATMA_TAKROR_SOAT", 24))

# --- Django REST Framework ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "EXCEPTION_HANDLER": "config.exceptions.xato_handler",
}

# Ilovalar `apps/` ichida bo'lgani uchun standart test qidiruvi ularni
# topa olmaydi — maxsus runner `apps/` dagi barcha ilovalarni tekshiradi.
TEST_RUNNER = "config.test_runner.AppTestRunner"

# --- JWT ---
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}

# --- Celery / Redis ---
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# --- Telegram bot (API dan foydalanish uchun) ---
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
BOT_API_BASE_URL = os.environ.get("BOT_API_BASE_URL", "http://127.0.0.1:8000/api")

# --- Production xavfsizligi (manage.py check --deploy) ---
# Nginx TLS va HTTP -> HTTPS redirect'ini o'zi boshqaradi (Strict-Transport-Security
# header'i ham nginx'da qo'yilgan). Quyidagilar Django tomonda qo'shimcha himoya.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
# SECURE_SSL_REDIRECT ni yoqmay qoldiramiz: redirect'ni nginx allaqachon qiladi
# (80 -> 443), va Django darajasida yoqish bot'ning lokal yo'lini
# (BOT_API_BASE_URL=http://127.0.0.1:8000/api) buzadi.
SECURE_SSL_REDIRECT = os.environ.get(
    "SECURE_SSL_REDIRECT", "False"
).lower() in ("true", "1", "yes")
# security.W008 ni jimga olish: redirect mas'uliyati nginx'da.
SILENCED_SYSTEM_CHECKS = ["security.W008"]