# Generated by Django 6.1.1 on 2026-09-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitob', '0001_initial'),
        ('nusxa', '0001_initial'),
        ('oquvchi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbat_sanasi', models.DateTimeField(auto_now_add=True)),
                ('holati', models.CharField(choices=[('kutmoqda', 'Kutmoqda'), ('taklif_qilindi', 'Taklif qilindi'), ('yakunlandi', 'Yakunlandi'), ('bekor', 'Bekor')], default='kutmoqda', max_length=20)),
                ('taklif_vaqti', models.DateTimeField(blank=True, null=True)),
                ('taklif_muddati', models.DateTimeField(blank=True, null=True)),
                ('javob_vaqti', models.DateTimeField(blank=True, null=True)),
                ('bekor_sababi', models.CharField(blank=True, max_length=30)),
                ('ajratilgan_nusxa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbatlar', to='nusxa.nusxa')),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbat', to='kitob.kitob')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbatlar', to='oquvchi.oquvchi')),
            ],
            options={
                'ordering': ['navbat_sanasi'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('holati__in', ['kutmoqda', 'taklif_qilindi'])), fields=('kitob', 'oquvchi'), name='unique_active_queue'), models.UniqueConstraint(condition=models.Q(('holati', 'taklif_qilindi')), fields=('kitob',), name='one_pending_offer_per_book')],
            },
        ),
    ]
