# Generated by Django 6.1.1 on 2026-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0004_kitob_holati'),
        ('navbat', '0001_initial'),
        ('nusxa', '0001_initial'),
        ('oquvchi', '0006_ariza_sinf_oquvchi_sinf_ariza_ariza_holati_sana_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbat',
            name='javob',
            field=models.CharField(blank=True, choices=[('olaman', 'Olaman'), ('kerak_emas', 'Kerak emas')], max_length=20),
        ),
        migrations.AddField(
            model_name='navbat',
            name='taklif_xabari_yuborilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='navbat',
            index=models.Index(fields=['holati', 'taklif_muddati'], name='navbat_taklif_muddat_idx'),
        ),
    ]
