# Generated by Django 6.1.1 on 2026-09-13 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(db_index=True, max_length=300)),
                ('muallif', models.CharField(db_index=True, max_length=150)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('janr', models.CharField(choices=[('badiiy', 'Badiiy'), ('ilmiy', 'Ilmiy'), ('darslik', 'Darslik'), ('bolalar', 'Bolalar'), ('tarixiy', 'Tarixiy'), ('boshqa', 'Boshqa')], max_length=60)),
                ('nashr_yili', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2026)])),
                ('nashriyot', models.CharField(blank=True, max_length=150)),
                ('tavsif', models.TextField(blank=True)),
                ('qoshilgan_sana', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
