# Generated by Django 6.1.1 on 2026-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
