# Generated by Django 6.1.1 on 2026-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0002_alter_kitob_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='buyurtma_soni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kitob',
            name='narh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='kitob',
            name='til',
            field=models.CharField(blank=True, choices=[('ozbek_lotin', "O'zbek tili"), ('ozbek_krill', 'Узбек тили'), ('rus', 'Rus tili'), ('ingliz', 'Ingliz tili'), ('boshqa', 'Boshqa')], default='', max_length=30),
        ),
    ]
