# Generated by Django 6.1.1 on 2026-09-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0003_kitob_buyurtma_soni_kitob_narh_kitob_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='holati',
            field=models.CharField(choices=[('mavjud', 'Mavjud'), ('yoqolgan', "Yo'qolgan")], default='mavjud', max_length=20),
        ),
    ]
