# Generated by Django 6.1.1 on 2026-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0004_kitob_holati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='holati',
            field=models.CharField(choices=[('mavjud', 'Mavjud'), ('berilgan', 'Berilgan'), ('yoqolgan', "Yo'qolgan")], default='mavjud', max_length=20),
        ),
    ]
