# Generated by Django 6.1.1 on 2026-10-03 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berish', '0008_berish_kitob_asli_berish'),
        ('kitob', '0006_sinxron_kitob_holati'),
        ('oquvchi', '0009_oquvchi_rolni_tiklash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandQilish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holati', models.CharField(choices=[('kutmoqda', 'Tasdiqlash kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutmoqda', max_length=20)),
                ('izoh', models.CharField(blank=True, max_length=255)),
                ('so_rov_sanasi', models.DateTimeField(auto_now_add=True)),
                ('tasdiqlash_sanasi', models.DateTimeField(blank=True, null=True)),
                ('tasdiqlash_izohi', models.CharField(blank=True, max_length=255)),
                ('berish', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band_qilish', to='berish.berish')),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='band_qilishlar', to='kitob.kitob')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='band_qilishlar', to='oquvchi.oquvchi')),
                ('tasdiqlovchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasdiqlangan_bandlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Band qilish',
                'verbose_name_plural': 'Band qilishlar',
                'ordering': ['-so_rov_sanasi', '-id'],
                'indexes': [models.Index(fields=['holati', '-so_rov_sanasi'], name='band_holat_sana_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('holati', 'kutmoqda')), fields=('kitob',), name='band_kitob_bitta_kutmoqda')],
            },
        ),
    ]
